Correct I2S SD PIN allocation (not output) and add debug message
atuline/WLED pull request #206
Opened 2022-05-10 15:49 UTC by claudiosv

The M5 Stick Plus has an internal I2S PDM MIC. The PINs are 34 for SD and 0 for WS. The PIN manager logic is as follows:
```
if (gpio <  6) return  true;
if (gpio < 12) return false; //SPI flash pins
if (gpio < 34) return true;
if (gpio < 40 && !output) return true; //34-39 input only

return false;
```

In the PDM audio source, the PIN request for SD is incorrectly marked as an output PIN, meaning in this IF cascade, the request for PIN 34 reaches the final return false (and thus no PIN assigned). By correcting the request with output=false, the bug is fixed. I was shocked there was no debug message for this either, so I added one.

2022-05-25 19:12 UTC, softhack007 reviewed
The change in audio_source.h might be OK, if other digital I2S mics will also work with SD being an input-only pin without any pullups/pulldowns. @FHeilmann what do you think?

The change in pin_manager also makes sense to me, however we would deviate from "upstream" (Aircookie WLED) if we merge it. Might be better to submit this to upstream. @THATDONFC what's your opinion on this?

2022-05-30 11:57 UTC, FHeilmann commented
> The change in audio_source.h might be OK, if other digital I2S mics will also work with SD being an input-only pin without any pullups/pulldowns. @FHeilmann what do you think?
> 
> The change in pin_manager also makes sense to me, however we would deviate from "upstream" (Aircookie WLED) if we merge it. Might be better to submit this part to upstream. @THATDONFC what's your opinion on this?

Agreed on both accounts. The change in audio source seems like a mistake on my end, but the other changes should be submitted to AC WLED and are out of scope for the SR fork.

-Florian

2022-06-02 15:17 UTC, softhack007 commented
Hi @claudiosv, 
Thank you for your effort and contributions.
Please update the PR so it only contains the changed call of `!pinManager.allocatePin(...)` in [audio_source.h].

- Frank.

2022-06-07 14:45 UTC, softhack007 requested changes
as discussed - please change the PR so that only audio_source.h is modified.

2022-06-11 16:56 UTC, claudiosv commented
@softhack007 @FHeilmann How does it look now?

2022-06-11 18:01 UTC, softhack007 approved these changes

2022-06-11 18:28 UTC, softhack007 commented
Looks good, thanks 👍

2022-06-11 18:29 UTC, merged